<template>
<div class="list-details">
  <div class="box-area">
    <h3>保函详情</h3>
    <div>
        <ul class="clearfix">
            <li   v-for="item in formList">
                <label>{{item.label}}：</label>
                <span>{{item.value}}</span>
            </li>
        </ul>
    </div>
            <!-- <li>
                <label>预担保单号</label>
                <span>111</span>
            </li>
            <li>
                <label>担保单号</label>
                <span>111</span>
            </li>
            <li>
                <label>项目名称</label>
                <span>111</span>
            </li>
            <li>
                <label>项目类型</label>
                <span>111</span>
            </li>
            <li>
                <label>投保人姓名</label>
                <span>111</span>
            </li>
            <li>
                <label>投保人统一信用社会代码</label>
                <span>111</span>
            </li>
            <li>
                <label>项目标段编号</label>
                <span>111</span>
            </li>
            <li>
                <label>招标人名称</label>
                <span>111</span>
            </li>
            <li>
                <label>招标人统一信用社会代码</label>
                <span>111</span>
            </li>
             <li>
                <label>招标人地址</label>
                <span>111</span>
            </li>
            <li>
                <label>招标人联系电话</label>
                <span>111</span>
            </li>
            <li>
                <label>担保保费</label>
                <span>111</span>
            </li>
             <li>
                <label>担保保额</label>
                <span>111</span>
            </li>
            <li>
                <label>起保日期</label>
                <span>111</span>
            </li>
            <li>
                <label>终保日期</label>
                <span>111</span>
            </li>
            <li>
                <label>担保期限(天)</label>
                <span>111</span>
            </li>
            <li>
                <label>特别条款</label>
                <span>111</span>
            </li>
            <li>
                <label>第三方合作公司</label>
                <span>111</span>
            </li>
            <li>
                <label>担保状态</label>
                <span>111</span>
            </li>
            <li>
                <label>保函申请状态</label>
                <span>111</span>
            </li>
            <li>
                <label>保函申请审核状态</label>
                <span>111</span>
            </li>
            <li>
                <label>支付状态</label>
                <span>111</span>
            </li>
            <li>
                <label>支付方式</label>
                <span>111</span>
            </li>
            <li>
                <label>保函申请时间</label>
                <span>111</span>
            </li>
             <li>
                <label>保函审核时间</label>
                <span>111</span>
            </li>
            <li>
                <label>保函提交时间</label>
                <span>111</span>
            </li>
            <li>
                <label>结算时间</label>
                <span>111</span>
            </li>
            <li>
                <label>保函受理时间</label>
                <span>111</span>
            </li>
            <li>
                <label>批改保函时间</label>
                <span>111</span>
            </li>
        </ul>
    </div>
      <h3>开票信息</h3>
      <div>
        <ul class="clearfix">
            <li>
               <label>开票类型</label>
               <span>111</span>
            </li>
            <li>
               <label>开票申请时间</label>
               <span>111</span>
            </li>
            <li>
               <label>开票状态</label>
               <span>111</span>
            </li>
            <li>
               <label>纳税人识别号</label>
               <span>111</span>
            </li>
            <li>
               <label>发票抬头</label>
               <span>111</span>
            </li>
            <li>
               <label>e-mail</label>
               <span>111</span>
            </li>
            <li>
               <label>收件人</label>
               <span>111</span>
            </li>
            <li>
               <label>收件人手机号</label>
               <span>111</span>
            </li>
            <li>
               <label>收件地址</label>
               <span>111</span>
            </li>
            <li>
               <label>注册地址</label>
               <span>111</span>
            </li>
            <li>
               <label>开户行</label>
               <span>111</span>
            </li>
            <li>
               <label>开户账号</label>
               <span>111</span>
            </li>
            <li>
               <label>联系电话</label>
               <span>111</span>
            </li>
            <li>
               <label>电子发票下载地址</label>
               <span>111</span>
            </li>
            <li>
               <label>快递公司</label>
               <span>111</span>
            </li>
            <li>
               <label>快递单号</label>
               <span>111</span>
            </li>
        </ul>
      </div>
      <h3>退保信息</h3>
      <div>
        <ul>
            <li>
                <label>退保状态</label>
               <span>111</span>
            </li>
            <li>
                <label>退保申请时间</label>
               <span>111</span>
            </li>
            <li>
                <label>退保原因</label>
               <span>111</span>
            </li>
            <li>
                <label>账户名</label>
               <span>111</span>
            </li>
            <li>
                <label>退款账户开户行</label>
               <span>111</span>
            </li>
            <li>
                <label>退款银行账户</label>
               <span>111</span>
            </li>
            <li>
                <label>退款处理结果</label>
               <span>111</span>
            </li>
        </ul>
      </div>
      <h3>理赔信息</h3>
      <div>
        <ul>
            <li>
                <label>理赔状态</label>
               <span>111</span>
            </li>
            <li>
                <label>理赔申请时间</label>
               <span>111</span>
            </li>
            <li>
                <label>理赔原因</label>
               <span>111</span>
            </li>
             <li>
                <label>理赔人姓名</label>
               <span>111</span>
            </li>
            <li>
                <label>理赔人联系方式</label>
               <span>111</span>
            </li>
            <li>
                <label>理赔处理结果</label>
               <span>111</span>
            </li>
        </ul>
      </div> -->
  </div>
</div>
</template>


<script>
export default {
  name: 'listDetails',
  props: {
    formList: {
      type: Array,
      default: function() {
        return [];
      }
    },
    },
  data() {
    return {
    }
  }
}   
</script>

<style lang="scss" scoped>
.list-details{
    .box-area{
        ul{
            padding:0;margin:0;list-style:none;
            li{
                width:33.33%;
                float:left;
                padding:0;margin:0;list-style:none;
                margin-bottom:10px;
                height:30px;
                line-height:30px;
                label{
                    width:160px;
                    display:inline-block;
                    text-align:right;
                }
                .el-input{
                    width:260px;
                }
            }
        }
    }
}
</style>

